table Projects
	lineageTag: 74ea25c6-b20d-4eb0-b0e8-17d6c3762367

	column 'Project Name'
		dataType: string
		lineageTag: fe9434cc-7704-4f7b-a85c-07f1fb917bff
		summarizeBy: none
		sourceColumn: Project Name

		annotation SummarizationSetBy = Automatic

	column 'Project Type'
		dataType: string
		lineageTag: 3f5a33da-e8d1-4f95-b3d5-0a94b9448215
		summarizeBy: none
		sourceColumn: Project Type

		annotation SummarizationSetBy = Automatic

	column 'Email PowerBI'
		dataType: string
		lineageTag: aa757eee-8674-46c8-9f26-b5f58d732bc2
		summarizeBy: none
		sourceColumn: Email PowerBI

		annotation SummarizationSetBy = Automatic

	column 'Project manager'
		dataType: string
		lineageTag: 762e6b5b-b4e9-465c-bf23-709da91aff5d
		summarizeBy: none
		sourceColumn: Project manager

		annotation SummarizationSetBy = Automatic

	partition Projects-66752533-1c45-49ad-b2fd-b08a58cb0072 = m
		mode: import
		queryGroup: DataModel
		source =
				let
				    Source = VSTS.Contents("https://dev.azure.com/fiveforty/_apis/projects?api-version=6.0"),
				    #"Imported JSON" = Json.Document(Source,65001),
				    value = #"Imported JSON"[value],
				    #"Converted to Table" = Table.FromList(value, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"name"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"name", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"name", "Project Name"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Project Name"}, #"_Project details", {"DevOpsProject"}, "Query1", JoinKind.LeftOuter),
				    #"Expanded Query2" = Table.ExpandTableColumn(#"Merged Queries", "Query1", {"Chef de projet", "Project type","Email PowerBI"}, {"Project manager", "Project Type","Email PowerBI"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Query2",{"Project manager"}),
				    #"Merged Queries1" = Table.FuzzyNestedJoin(#"Removed Columns", {"Project Name"}, #"Projects managers", {"Customer Key"}, "Projects managers", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true, NumberOfMatches=1, Threshold=0]),
				    #"Expanded Projects managers" = Table.ExpandTableColumn(#"Merged Queries1", "Projects managers", {"Account Manager"}, {"Project director"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded Projects managers", {"Project Name"}, #"Axonaut Projects", {"Team Project"}, "Query1", JoinKind.LeftOuter),
				    #"Expanded Query1" = Table.ExpandTableColumn(#"Merged Queries2", "Query1", {"Project manager"}, {"Project manager"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded Query1", "Custom", each if [Project manager] = "" or [Project manager] = null then [Project director] else [Project manager]),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom",{"Project director", "Project manager"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Custom", "Project manager"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Project manager", type text}})
				in
				    #"Changed Type1"

	annotation PBI_Id = e4e36db0-99cc-4e32-a988-62a51755bf56

	annotation LinkedQueryName = DevOpsProjects

	annotation PBI_QueryRelationships = {"columnCount":2,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/DevOpsProjects/Changed Type.{DevOpsProject,0}","Section1/DevOpsProjects/Changed Type.{Project,1}"],"ColumnCount":2,"KeyColumnNames":[],"ColumnIdentities":["Section1/DevOpsProjects/Changed Type.{DevOpsProject,0}","Section1/DevOpsProjects/Changed Type.{Project,1}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

